apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.stage }}-hello-world-java
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ .Values.stage }}-hello-world-java
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: {{ .Values.stage }}-hello-world-java
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: hello-world-java
        resources: {}
      restartPolicy: Always
