apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stage }}-hello-world-java
  labels:
    app: hello-world-java
    stage: {{ .Values.stage }}
spec:
  ports:
    - port: 9999
      nodePort: {{ .Values.nodePort }}
      name: nodeport
  selector:
    deployment: {{ .Values.stage }}-hello-world-java
  type: LoadBalancer
